### ISSUE TITLE
obvious installation instructions are missing.  

### ISSUE THREAD

**Issue by richlysakowski** [McGill-NLP/webllama#11]
We need crucially important installation instructions and explanations how to set this up locally.  I dug around and found some detailed instructions buried in the modelling folder, but these are for Linux only, and only show pip (python-only) installation instructions.

Please provide conda packages and installation instructions for installing locally on Windows 10 or Windows 11 Professional.

Thank you.

**Comment by xhluca** [comment]
Thank you for your interest! We do not plan to support non-WSL Windows due to the challenge of setting up CUDA and our lack of access to a Windows equiped with a GPU with sufficient memory to run LLaMA models. However, I would recommend exploring WSL 2 if you are unable to directly use a Linux-based OS like Ubuntu.
